version: '2'
services:
 calibre:
    image: asdlfkj31h/debian-calibre:0.2
    ports:
    - 5901:5901
    - 6901:6901
    volumes:
    - ./calibre:/headless/.config/calibre
    - ./library:/headless/Calibre Library

